steps:
# 1. Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-backend:$COMMIT_SHA', '.']

# 2. Push the container image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/my-backend:$COMMIT_SHA']

# 3. Deploy the container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
    - 'run'
    - 'deploy'
    - 'my-backend-service' # This is the service name we used before
    - '--image'
    - 'gcr.io/$PROJECT_ID/my-backend:$COMMIT_SHA'
    - '--region'
    - 'asia-south1' # Use the same region as before
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'

# Store the image in the registry
images:
- 'gcr.io/$PROJECT_ID/my-backend:$COMMIT_SHA'